# Generated by Django 4.1.5 on 2023-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_e_mail_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='e_mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
