# Generated by Django 4.1.5 on 2023-09-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_paid_alter_order_total_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_myuser_remove_cart_products_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(null=True)),
                ('paid', models.BooleanField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
