# Generated by Django 4.1.5 on 2023-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_payment_rename_phone_number_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_mail',
        ),
    ]
