# Generated by Django 4.1.5 on 2023-12-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profileimage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
