# Generated by Django 4.1.5 on 2023-09-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_subcategory_category'),
        ('user', '0009_basket_basketitem_delete_cart_basket_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(related_name='basket', to='user.basketitem'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.product'),
        ),
    ]
