# Generated by Django 4.1.5 on 2023-09-15 11:48

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_basket_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='sum',
            field=computed_property.fields.ComputedTextField(compute_from='calculation', default=2, editable=False),
            preserve_default=False,
        ),
    ]
