# Generated by Django 4.1.5 on 2023-09-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_basketitem_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
