# Generated by Django 4.1.5 on 2023-09-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_sum',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='sum',
        ),
    ]
