# Generated by Django 4.1.5 on 2023-09-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_basket_total_sum_remove_basketitem_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile'},
        ),
    ]
