# Generated by Django 4.1.5 on 2023-12-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='manage.deliverytype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('MC', 'MasterCard'), ('PP', 'PayPal'), ('AE', 'AmericanExpress'), ('E', 'Electron'), ('M', 'Maestro'), ('D', 'Delta'), ('C', 'Cash'), ('QR', 'QR-Code'), ('O', 'Online')], max_length=20),
        ),
    ]
