# Generated by Django 4.1.5 on 2023-12-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
