# Generated by Django 4.1.5 on 2023-12-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='delivery',
        ),
    ]
