# Generated by Django 4.1.5 on 2023-09-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='product',
        ),
    ]
