# Generated by Django 4.1.5 on 2023-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_post_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
