# Generated by Django 4.1.5 on 2023-12-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0008_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('Product', 'Category', 'Profile')}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.contenttype'),
        ),
    ]
