# Generated by Django 4.1.5 on 2023-12-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
    ]
