# Generated by Django 4.1.5 on 2023-12-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_image_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='src',
        ),
    ]
