# Generated by Django 4.1.5 on 2023-09-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sum',
        ),
    ]
