# Generated by Django 4.1.5 on 2023-09-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_order_status_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('V', 'Visa'), ('MC', 'MasterCard'), ('PP', 'PayPal'), ('AE', 'AmericanExpress'), ('E', 'Electron'), ('M', 'Maestro'), ('D', 'Delta'), ('C', 'Cash'), ('QR', 'QR-Code'), ('O', 'Online')], max_length=20),
        ),
    ]
