# Generated by Django 4.1.5 on 2023-09-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
        ('shop', '0027_remove_order_delivery_type_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage.deliverytype'),
            preserve_default=False,
        ),
    ]
