# Generated by Django 4.1.5 on 2023-09-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
