# Generated by Django 4.1.5 on 2023-10-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_review_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='published_at',
        ),
    ]
