# Generated by Django 4.1.5 on 2023-10-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_review_options_remove_review_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='count',
        ),
    ]
