# Generated by Django 4.1.5 on 2023-10-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_rename_amount_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date',
        ),
    ]
