# Generated by Django 4.1.5 on 2023-10-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_rename_img_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews_count',
            new_name='reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product'),
        ),
    ]
