# Generated by Django 4.1.5 on 2023-10-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_rename_reviews_count_product_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='old_price',
            new_name='sale_price',
        ),
    ]
