# Generated by Django 4.1.5 on 2023-10-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_rename_delivery_adress_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
