# Generated by Django 4.1.5 on 2023-12-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
